# House Price Prediction

## Exploratory Data Analysis (EDA)

### 1. Import Libraries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display plots inside notebook
%matplotlib inline

### 2. Load Dataset

In [4]:
df = pd.read_csv("../data/Housing.csv")

df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

### 3. Basic Inspection

In [5]:
print("Shape :", df.shape)

print("\nColumns :")
print(df.columns)

print("\nInformation :")
df.info()

Shape : (545, 13)

Columns :
Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='str')

Information :
<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: int64(6), str(7)
memory usage: 55.5 KB

In [6]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

### 4. Missing Values

In [7]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

### 5. Duplicate Records

In [8]:
df.duplicated().sum()

np.int64(0)

### 7. Data Types

In [9]:
df.dtypes

price               int64
area                int64
bedrooms            int64
bathrooms           int64
stories             int64
mainroad              str
guestroom             str
basement              str
hotwaterheating       str
airconditioning       str
parking             int64
prefarea              str
furnishingstatus      str
dtype: object

### 8. Feature Classification

In [10]:
numerical_columns = df.select_dtypes(include=["int64", "float64"]).columns

categorical_columns = df.select_dtypes(include=["object"]).columns

print("Numerical Columns")
print(numerical_columns)

print("\nCategorical Columns")
print(categorical_columns)

Numerical Columns
Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'parking'], dtype='str')

Categorical Columns
Index(['mainroad', 'guestroom', 'basement', 'hotwaterheating',
       'airconditioning', 'prefarea', 'furnishingstatus'],
      dtype='str')

C:\Users\Amit Singh\AppData\Local\Temp\ipykernel_13704\2838128473.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=["object"]).columns

## 9. Import Visualization Libraries

In [ ]:
import seaborn as sns

# Plot Settings
plt.style.use("ggplot")
plt.rcParams["figure.figsize"] = (8, 5)

## 10. Univariate Analysis

In [ ]:
df.hist(figsize=(15, 10), bins=20)
plt.tight_layout()
plt.show()

### Price Distribution

In [ ]:
plt.figure(figsize=(8,5))

sns.histplot(df["price"], kde=True)

plt.title("House Price Distribution")
plt.xlabel("Price")
plt.ylabel("Count")

plt.show()

### Area Distribution

In [ ]:
plt.figure(figsize=(8,5))

sns.histplot(df["area"], kde=True)

plt.title("Area Distribution")

plt.show()

### Bedrooms

In [ ]:
sns.countplot(x="bedrooms", data=df)

plt.title("Bedrooms Count")

plt.show()

In [ ]:
sns.countplot(x="bathrooms", data=df)

plt.title("Bathrooms Count")

plt.show()

In [ ]:
sns.countplot(x="stories", data=df)

plt.title("Stories Count")

plt.show()

In [ ]:
sns.countplot(x="furnishingstatus", data=df)

plt.title("Furnishing Status")

plt.show()

In [ ]:
sns.countplot(x="parking", data=df)

plt.title("Parking")

plt.show()